<?php

namespace ContainerLxO2VGN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ALKenoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aLKeno_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aLKeno_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\DefaultController::login' => ['privates', '.service_locator.emOhpFj', 'get_ServiceLocator_EmOhpFjService', true],
            'App\\Controller\\DefaultController::pruebasAction' => ['privates', '.service_locator.SUXZ7L4', 'get_ServiceLocator_SUXZ7L4Service', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.zXCb2dE', 'get_ServiceLocator_ZXCb2dEService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\DefaultController:login' => ['privates', '.service_locator.emOhpFj', 'get_ServiceLocator_EmOhpFjService', true],
            'App\\Controller\\DefaultController:pruebasAction' => ['privates', '.service_locator.SUXZ7L4', 'get_ServiceLocator_SUXZ7L4Service', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.zXCb2dE', 'get_ServiceLocator_ZXCb2dEService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\DefaultController::login' => '?',
            'App\\Controller\\DefaultController::pruebasAction' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\DefaultController:login' => '?',
            'App\\Controller\\DefaultController:pruebasAction' => '?',
            'App\\Controller\\UserController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
